### ISSUE TITLE
Rename and reorder chapters

### ISSUE THREAD

**Issue by fraxken** [fraxken/ebook_nodejs#13]
Hello :wave:

In order to be able to generate PDF version, we need to order the folders and files (else they will be concatened in the wrong order).

![image](https://user-images.githubusercontent.com/4438263/202359418-82b01013-7c7e-4df9-a205-8b2c94d231bb.png)

I started the work on the french version. It require to fix all the markdown links.

**Comment by fraxken** [comment]
By the way, for testing PDF generation

```
node .\scripts\generatePdf.js --lang fr
```

**Comment by alexandrecoin** [comment]
Hi ! 👋
I'd be happy to give a hand on this.
As you seem to be taking care of the French version, would you like me to do the English one ?

**Comment by fraxken** [comment]
Hello 👋 

I gladly accept your help @alexandrecoin! Yes do not hesitate to take care of the English one.

**Comment by fraxken** [comment]
@alexandrecoin If you are motivated you can finish french (I was thinking doing it but I don't have much time in the coming days).

**Comment by alexandrecoin** [comment]
@fraxken  Yes, will do. 👍

**Comment by alexandrecoin** [comment]
But first, I noticed there's actually an issue with the links that appear to be broken on both updated French and English versions. I'll give this a look.

**Comment by fraxken** [comment]
Closing as I finished chapter re-order. Opened an issue for improvment of PDF generation: https://github.com/fraxken/ebook_nodejs/issues/18
