### ISSUE TITLE
There is no content on heap memory

### ISSUE THREAD

**Issue by ajubin** [fraxken/ebook_nodejs#17]
Hi, 

I really like this book and recommend it frequently. 
Few months ago I had to handle a memory leak so I looked at this topic but there was no content in this book. 

It could be interessting to add some stuff

**Comment by fraxken** [comment]
Hello 👋 

Hmm I have to look into this, I remember reading quite few cool articles on the subject.

I known @vdeturckheim has some experience on the area, he also made a talk [Finding memory leaks and CPU bottlenecks with Node.js debug tools](https://www.youtube.com/watch?v=F_qshjijxlE). Maybe he can recommand few resources on the subject?

There is also the [official Node.js guide](https://nodejs.org/en/docs/guides/diagnostics/memory/using-gc-traces/) about `--trace-gc` made by @tony-go (He made some good french videos that are in the french version, sorry 😂).

**Comment by fraxken** [comment]
More links coming soon in/with https://github.com/fraxken/ebook_nodejs/pull/24/files
