### ISSUE TITLE
add contributors

### ISSUE THREAD

**Issue by fraxken** [fraxken/ebook_nodejs#2]

**Comment by fraxken** [comment]
@all-contributors please add @fraxken content, blog, doc, example, ideas

**Comment by fraxken** [comment]
@all-contributors please add @Rossb0b for doc, translation

**Comment by fraxken** [comment]
@all-contributors please add @PierreDemailly for doc, translation

**Comment by fraxken** [comment]
@all-contributors please add @tony-go for review, talk

**Comment by fraxken** [comment]
@all-contributors please add @Kawacrepe for review

**Comment by fraxken** [comment]
@all-contributors please add @AlexandreMalaj for review

**Comment by fraxken** [comment]
@all-contributors please add @vdeturckheim for review

**Comment by tony-go** [comment]
😍
